# 演習
第1講の演習です。

## Tensor同士の演算
以下のTensor`a`と`b`の間で、以下の演算子を使って演算を行い、結果を表示しましょう。  
和: +  
差: -  
積: *  
商（小数）: /  
商（整数）: //  
余り: %  
`a`は行列で`b`はベクトルなので、ブロードキャストが必要になります。

In [1]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])
b = torch.tensor([1, 2, 3.])

# 和
print(a+b)

# 差
print(a-b)

# 積
print(a*b)

# 商（小数）
print(a/b)

# 商（整数）
print(a//b)

# 余り
print(a%b)

tensor([[2., 4., 6.],
        [5., 7., 9.]])
tensor([[0., 0., 0.],
        [3., 3., 3.]])
tensor([[ 1.,  4.,  9.],
        [ 4., 10., 18.]])
tensor([[1.0000, 1.0000, 1.0000],
        [4.0000, 2.5000, 2.0000]])
tensor([[1., 1., 1.],
        [4., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 1., 0.]])


## 解答例
以下は、どうしても手がかりがないときのみ参考にしましょう。

In [ ]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])
b = torch.tensor([1, 2, 3.])

# 和
print(a + b)

# 差
print(a - b)

# 積
print(a * b)

# 商（小数）
print(a / b)

# 商（整数）
print(a // b)

# 余り
print(a % b)